#extra_suffix = "NAIIVE" # $env:BUILD_NAME="NA\\\\VE"
production = "yes"
optimize = "size"
use_lto = "full"
deprecated = "no"
#disable_3d = "yes" # Disable 3D nodes for a smaller binary.
#modules_enabled_by_default = "no"
module_visual_script_enabled = "no" # Required to run scripts made using VisualScript.
#module_disable_advanced_gui_enabled = "no" # Disable advanced GUI nodes and behaviors such as Tree and GraphEdit.
#module_minizip_enabled = "no" # Required to run projects that use data packed into a ZIP archive instead of a PCK.
#module_arkit_enabled = "no" # Required for AR/VR support on iOS. Has no effect on other platforms.
#module_bmp_enabled = "no" # Required to load BMP images.
#module_bullet_enabled = "no" # Advanced 3D physics engine (GodotPhysics is always compiled in).
#module_camera_enabled = "no" # AR/VR camera support (unrelated to Camera nodes).
#module_csg_enabled = "no" # Required to use Constructive Solid Geometry nodes.
#module_dds_enabled = "no" # Required to load DirectDraw Surface images.
#module_enet_enabled = "no" # Required to use NetworkedMultiplayerENet and NetworkedMultiplayerPeer.
#module_freetype_enabled = "no" # Required to render DynamicFonts. Bitmap fonts can still be used without FreeType.
#module_gdnative_enabled = "no" # Required to load GDNative libraries.
#module_gdscript_enabled = "no" # Required to run scripts written in GDScript.
#module_gridmap_enabled = "no" # Required to use GridMap nodes.
#module_hdr_enabled = "no" # Required to load Radiance HDR images.
#module_jpg_enabled = "no" # Required to load JPEG images.
#module_jsonrpc_enabled = "no" # Required to use the JSONRPC class.
#module_mbedtls_enabled = "no" # Required to make HTTPS requests.
#module_minimp3_enabled = "no" # Required to play back MP3 sounds in AudioStreamPlayer.
#module_mobile_vr_enabled = "no" # Required to use VR on Android and iOS.
#module_mono_enabled = "no" # Required to run scripts written in C#.
#module_navigation_enabled = "no" # Required to use NavigationServer.
#module_ogg_enabled = "no" # Required to play WebM (VP8) videos with sound in VideoPlayer. See also `stb_vorbis` and `vorbis`.
#module_opensimplex_enabled = "no" # Required to use OpenSimplexNoise and NoiseTextures that rely on it.
#module_opus_enabled = "no" # Required to play WebM (VP9) videos with sound in VideoPlayer.
#module_regex_enabled = "no" # Required to use the RegEx class.
#module_stb_vorbis_enabled = "no" # Required to play back Ogg Vorbis sounds in AudioStreamPlayer.
#module_tga_enabled = "no" # Required to load TrueVision Targa images.
#module_theora_enabled = "no" # Required to play back Ogg Theora videos in VideoPlayer.
#module_tinyexr_enabled = "no" # Required to load EXR images.
#module_upnp_enabled = "no" # Required to use the UPNP classes for network discovery and automatic port forwarding.
#module_visual_script_enabled = "no" # Required to run scripts made using VisualScript.
#module_vorbis_enabled = "no" # Required to play WebM (VP8) videos with sound in VideoPlayer. See also `ogg`.
#module_webm_enabled = "no" # Required to play WebM (VP8 and VP9) videos in VideoPlayer. See also `ogg` and `vorbis`.
#module_webrtc_enabled = "no" # Required to use WebRTC connections.
#module_websocket_enabled = "no" # Required to use WebSocket connections.
#module_webxr_enabled = "no" # Required to run AR/VR on browsers.