name: 🟢 Android Builds
on:
  workflow_call:

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: 3.x
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-builds:
    runs-on: "ubuntu-24.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            cache-name: android-editor
            target: release_debug
            tools: true

          - name: Template (target=release, tools=no)
            cache-name: android-template
            target: release
            tools: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation (armv7)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} android_arch=armv7
          platform: android
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Generate Godot templates
        if: ${{ !matrix.tools }}
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..

      - name: Prepare artifact
        run: |
          mkdir -p bin/android
          if [ -d "platform/android/java/lib/build/outputs/aar" ]; then
            cp platform/android/java/lib/build/outputs/aar/* bin/android/
          fi
          if [ -d "platform/android/java/app/build/outputs/apk" ]; then
            cp platform/android/java/app/build/outputs/apk/*/* bin/android/
          fi

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
          path: bin/android/
